name: Unit Tests
on: push

jobs:
  tests:
    name: run unit tests
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci     
      - name: test
        run: npm run test
      - name: make test-coverage  
        run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
    finish:
      needs: tests
      runs-on: windows-latest
      steps:
        - name: Coveralls Finished
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Upload code coverage to Coveralls
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: ./coverage/lcov.info
        env:
          DEFAULT_BRANCH: main
